name: PyPI Publish

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: pip install setuptools wheel twine

      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PYPI_VERSION: ${{ github.ref }}
        run: |
          python ./setup.py bdist_wheel sdist
          twine upload ./dist/*
